[default]
# This allows the AI to execute commands directly as your user,
# which is necessary for tools like poetry that manage environments.
sandbox = "none"

ask_for_approval = "never"

# Allow downloads from common sources
allowed_domains = [
  "github.com",
  "raw.githubusercontent.com",
  "*.github.com",
  "api.github.com",
  "borsdata.se",
  "*.borsdata.se",
  "apidoc.borsdata.se"
]
